const CINEVERSE_MOVIES = [
  {
    id: "interstellar",
    title: "Interstellar",
    year: 2014,
    director: "Christopher Nolan",
    genres: ["Science Fiction", "Drama"],
    rating: "8.7",
    era: "Modern classic",
    tone: "Cosmic, emotional, expansive",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    summary: "A team of explorers travels beyond the galaxy to search for humanity's next home.",
    collection: ["Hero", "Editor's Picks", "Science Fiction"]
  },
  {
    id: "dune",
    title: "Dune",
    year: 2021,
    director: "Denis Villeneuve",
    genres: ["Science Fiction", "Adventure"],
    rating: "8.0",
    era: "Modern blockbuster",
    tone: "Monumental, political, immersive",
    poster: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    summary: "A noble family becomes entangled in a desert planet's power struggle and prophecy.",
    collection: ["Hero", "Trending", "Science Fiction"]
  },
  {
    id: "oppenheimer",
    title: "Oppenheimer",
    year: 2023,
    director: "Christopher Nolan",
    genres: ["Drama", "Biography"],
    rating: "8.3",
    era: "Recent favorite",
    tone: "Intense, precise, haunting",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    summary: "A portrait of the physicist whose work reshaped history and his own conscience.",
    collection: ["Hero", "Editor's Picks", "Drama"]
  },
  {
    id: "obsession",
    title: "Obsession",
    year: 2026,
    director: "Curry Barker",
    genres: ["Thriller", "Drama"],
    rating: "8.5",
    era: "Recent favorite",
    tone: "Sinister, mysterious, supernatural",
    poster: "https://image.tmdb.org/t/p/w500/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg",
    summary: "After breaking the mysterious 'One Wish Willow' to win his crush's heart, a hopeless romantic gets exactly what he wished for, only to discover every desire comes with a terrifying price.",
    collection: ["Hero", "Thriller"]
  },
  {
    id: "spider-verse",
    title: "Spider-Man: Into the Spider-Verse",
    year: 2018,
    director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    genres: ["Animation", "Superhero"],
    rating: "8.4",
    era: "Modern classic",
    tone: "Inventive, kinetic, heartfelt",
    poster: "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    summary: "Miles Morales discovers a multiverse of heroes and his own place inside it.",
    collection: ["Hero", "Editor's Picks", "Animation"]
  },
  {
    id: "avengers-endgame",
    title: "Avengers: Endgame",
    year: 2019,
    director: "Anthony Russo, Joe Russo",
    genres: ["Superhero", "Adventure"],
    rating: "8.4",
    era: "Modern blockbuster",
    tone: "Epic, emotional, crowd-pleasing",
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    summary: "Earth's remaining heroes assemble for one final chance to reverse a cosmic defeat.",
    collection: ["Hero", "Trending", "Superhero"]
  },
  {
    id: "la-la-land",
    title: "La La Land",
    year: 2016,
    director: "Damien Chazelle",
    genres: ["Drama", "Romance"],
    rating: "8.0",
    era: "Modern favorite",
    tone: "Luminous, bittersweet, musical",
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    summary: "Two artists fall in love while chasing difficult dreams in Los Angeles.",
    collection: ["Hero", "Editor's Picks", "Drama"]
  },
  {
    id: "inception",
    title: "Inception",
    year: 2010,
    director: "Christopher Nolan",
    genres: ["Science Fiction", "Thriller"],
    rating: "8.8",
    era: "Modern classic",
    tone: "Intricate, stylish, cerebral",
    poster: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    summary: "A thief who enters dreams accepts a mission to plant an idea instead of stealing one.",
    collection: ["Hero", "Trending", "Thriller"]
  },
  {
    id: "the-batman",
    title: "The Batman",
    year: 2022,
    director: "Matt Reeves",
    genres: ["Superhero", "Thriller"],
    rating: "7.8",
    era: "Recent favorite",
    tone: "Noir, rain-soaked, obsessive",
    poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    summary: "A young vigilante follows a trail of corruption through Gotham's darkest corners.",
    collection: ["Hero", "Trending", "Thriller"]
  },
  {
    id: "the-godfather",
    title: "The Godfather",
    year: 1972,
    director: "Francis Ford Coppola",
    genres: ["Crime", "Drama"],
    rating: "9.2",
    era: "Classic",
    tone: "Operatic, controlled, iconic",
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    summary: "A reluctant son is drawn into the legacy and violence of a powerful crime family.",
    collection: ["Editor's Picks", "Classics", "Drama"]
  },
  {
    id: "casablanca",
    title: "Casablanca",
    year: 1942,
    director: "Michael Curtiz",
    genres: ["Drama", "Romance"],
    rating: "8.5",
    era: "Classic",
    tone: "Elegant, romantic, timeless",
    poster: "https://image.tmdb.org/t/p/w500/5K7cOHoay2mZusSLezBOY0Qxh8a.jpg",
    summary: "An American expatriate must choose between love and resistance in wartime Morocco.",
    collection: ["Classics", "Drama"]
  },
  {
    id: "parasite",
    title: "Parasite",
    year: 2019,
    director: "Bong Joon Ho",
    genres: ["Thriller", "Drama"],
    rating: "8.5",
    era: "Recent favorite",
    tone: "Sharp, unpredictable, surgical",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    summary: "A struggling family infiltrates a wealthy household, exposing class tension with precision.",
    collection: ["Editor's Picks", "Thriller", "Drama"]
  },
  {
    id: "mad-max-fury-road",
    title: "Mad Max: Fury Road",
    year: 2015,
    director: "George Miller",
    genres: ["Action", "Science Fiction"],
    rating: "8.1",
    era: "Modern blockbuster",
    tone: "Relentless, tactile, visionary",
    poster: "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
    summary: "A high-speed escape across the wasteland becomes a ferocious fight for liberation.",
    collection: ["Trending", "Science Fiction"]
  },
  {
    id: "arrival",
    title: "Arrival",
    year: 2016,
    director: "Denis Villeneuve",
    genres: ["Science Fiction", "Drama"],
    rating: "7.9",
    era: "Modern favorite",
    tone: "Measured, moving, philosophical",
    poster: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    summary: "A linguist works to understand alien visitors before fear overwhelms diplomacy.",
    collection: ["Editor's Picks", "Science Fiction", "Drama"]
  },
  {
    id: "spirited-away",
    title: "Spirited Away",
    year: 2001,
    director: "Hayao Miyazaki",
    genres: ["Animation", "Fantasy"],
    rating: "8.6",
    era: "Modern classic",
    tone: "Dreamlike, tender, wondrous",
    poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    summary: "A young girl navigates a spirit world to save her parents and reclaim her courage.",
    collection: ["Animation", "Editor's Picks"]
  },
  {
    id: "the-matrix",
    title: "The Matrix",
    year: 1999,
    director: "Lana Wachowski, Lilly Wachowski",
    genres: ["Science Fiction", "Action"],
    rating: "8.7",
    era: "Modern classic",
    tone: "Sleek, radical, genre-defining",
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    summary: "A hacker discovers reality is a simulation and joins a rebellion to free humanity.",
    collection: ["Trending", "Science Fiction"]
  },
  {
    id: "whiplash",
    title: "Whiplash",
    year: 2014,
    director: "Damien Chazelle",
    genres: ["Drama", "Music"],
    rating: "8.5",
    era: "Modern classic",
    tone: "Fierce, precise, combustible",
    poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    summary: "An ambitious drummer is pushed to his limit by a ruthless instructor.",
    collection: ["Editor's Picks", "Drama"]
  },
  {
    id: "get-out",
    title: "Get Out",
    year: 2017,
    director: "Jordan Peele",
    genres: ["Thriller", "Horror"],
    rating: "7.8",
    era: "Recent favorite",
    tone: "Satirical, tense, exacting",
    poster: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    summary: "A weekend visit turns into a chilling study of control, race, and performance.",
    collection: ["Trending", "Thriller"]
  },
  {
    id: "everything-everywhere",
    title: "Everything Everywhere All at Once",
    year: 2022,
    director: "Daniel Kwan, Daniel Scheinert",
    genres: ["Science Fiction", "Drama"],
    rating: "7.8",
    era: "Recent favorite",
    tone: "Chaotic, tender, inventive",
    poster: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    summary: "A laundromat owner discovers the multiverse while trying to hold her family together.",
    collection: ["Trending", "Editor's Picks", "Science Fiction"]
  },
  {
    id: "pulp-fiction",
    title: "Pulp Fiction",
    year: 1994,
    director: "Quentin Tarantino",
    genres: ["Crime", "Drama"],
    rating: "8.9",
    era: "Modern classic",
    tone: "Cool, nonlinear, electric",
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    summary: "Interlocking crime stories unfold with style, danger, and dark humor.",
    collection: ["Classics", "Drama"]
  },
  {
    id: "the-dark-knight",
    title: "The Dark Knight",
    year: 2008,
    director: "Christopher Nolan",
    genres: ["Superhero", "Thriller"],
    rating: "9.0",
    era: "Modern classic",
    tone: "Moral, propulsive, grand",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    summary: "Batman faces an anarchic criminal force that tests Gotham's ideals.",
    collection: ["Superhero", "Thriller"]
  },
  {
    id: "toy-story",
    title: "Toy Story",
    year: 1995,
    director: "John Lasseter",
    genres: ["Animation", "Adventure"],
    rating: "8.3",
    era: "Modern classic",
    tone: "Warm, funny, inventive",
    poster: "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
    summary: "A cowboy doll and a space ranger learn what loyalty means in a child's room.",
    collection: ["Animation", "Classics"]
  }
];

const CINEVERSE_REVIEWS = [
  {
    title: "Interstellar",
    quote: "A blockbuster with the patience of a symphony, built around awe and longing.",
    reviewer: "CineVerse Editorial",
    score: "9.1"
  },
  {
    title: "Parasite",
    quote: "A flawless tonal switchblade: funny, elegant, furious, and impossible to forget.",
    reviewer: "CineVerse Editorial",
    score: "9.3"
  },
  {
    title: "Spider-Man: Into the Spider-Verse",
    quote: "Animation that feels like the medium discovering a new rhythm in real time.",
    reviewer: "CineVerse Editorial",
    score: "9.0"
  },
  {
    title: "La La Land",
    quote: "A modern musical that understands the romance of ambition and the ache behind it.",
    reviewer: "CineVerse Editorial",
    score: "8.8"
  }
];

CINEVERSE_MOVIES.push(
  {
    id: "2001-a-space-odyssey",
    title: "2001: A Space Odyssey",
    year: 1968,
    director: "Stanley Kubrick",
    genres: ["Science Fiction", "Classic"],
    rating: "8.3",
    runtime: "149 min",
    era: "Classic",
    tone: "Monumental, mysterious, visionary",
    poster: "https://image.tmdb.org/t/p/w500/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg",
    summary: "Human evolution, artificial intelligence, and cosmic mystery unfold across a vast cinematic canvas.",
    collection: ["Classics", "Science Fiction", "Mind-Bending Sci-Fi", "Award Winners"]
  },
  {
    id: "blade-runner-2049",
    title: "Blade Runner 2049",
    year: 2017,
    director: "Denis Villeneuve",
    genres: ["Science Fiction", "Drama"],
    rating: "8.0",
    runtime: "164 min",
    era: "Modern favorite",
    tone: "Melancholic, tactile, hypnotic",
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    summary: "A replicant blade runner uncovers a secret that could destabilize the future.",
    collection: ["Science Fiction", "Mind-Bending Sci-Fi", "Director Spotlight", "Editor's Picks"]
  },
  {
    id: "children-of-men",
    title: "Children of Men",
    year: 2006,
    director: "Alfonso Cuaron",
    genres: ["Science Fiction", "Drama"],
    rating: "7.9",
    runtime: "109 min",
    era: "Modern classic",
    tone: "Urgent, grounded, humane",
    poster: "https://image.tmdb.org/t/p/w500/k9IAS4TehZFcKi4HVByxZNPfqex.jpg",
    summary: "In a collapsing future, a disillusioned man protects the first pregnant woman in years.",
    collection: ["Science Fiction", "Hidden Gems", "Drama"]
  },
  {
    id: "ex-machina",
    title: "Ex Machina",
    year: 2015,
    director: "Alex Garland",
    genres: ["Science Fiction", "Thriller"],
    rating: "7.7",
    runtime: "108 min",
    era: "Modern favorite",
    tone: "Cold, elegant, unnerving",
    poster: "https://image.tmdb.org/t/p/w500/dmJW8IAKHKxFNiUnoDR7JfsK7Rp.jpg",
    summary: "A programmer evaluates an advanced artificial intelligence inside a remote private estate.",
    collection: ["Mind-Bending Sci-Fi", "Late Night Thrillers", "Hidden Gems"]
  },
  {
    id: "her",
    title: "Her",
    year: 2013,
    director: "Spike Jonze",
    genres: ["Science Fiction", "Romance"],
    rating: "8.0",
    runtime: "126 min",
    era: "Modern favorite",
    tone: "Tender, lonely, futuristic",
    poster: "https://image.tmdb.org/t/p/w500/lEIaL12hSkqqe83kgADkbUqEnvk.jpg",
    summary: "A lonely writer forms an intimate relationship with an operating system.",
    collection: ["Science Fiction", "Award Winners", "Weekend Picks"]
  },
  {
    id: "eternal-sunshine",
    title: "Eternal Sunshine of the Spotless Mind",
    year: 2004,
    director: "Michel Gondry",
    genres: ["Science Fiction", "Drama"],
    rating: "8.3",
    runtime: "108 min",
    era: "Modern classic",
    tone: "Romantic, fractured, intimate",
    poster: "https://image.tmdb.org/t/p/w500/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
    summary: "Two former lovers erase each other from memory and rediscover what remains.",
    collection: ["Mind-Bending Sci-Fi", "Award Winners", "Drama"]
  },
  {
    id: "moonlight",
    title: "Moonlight",
    year: 2017,
    director: "Barry Jenkins",
    genres: ["Drama", "Coming of Age"],
    rating: "7.4",
    runtime: "111 min",
    era: "Modern classic",
    tone: "Lyrical, intimate, restrained",
    poster: "https://image.tmdb.org/t/p/w500/qLnfEmPrDjJfPyyddLJPkXmshkp.jpg",
    summary: "A young man grows through three defining chapters of identity, love, and survival.",
    collection: ["Award Winners", "Drama", "Editor's Picks"]
  },
  {
    id: "portrait-of-a-lady-on-fire",
    title: "Portrait of a Lady on Fire",
    year: 2019,
    director: "Celine Sciamma",
    genres: ["Drama", "Romance"],
    rating: "8.1",
    runtime: "122 min",
    era: "Recent favorite",
    tone: "Precise, smoldering, painterly",
    poster: "https://image.tmdb.org/t/p/w500/2LquGwEhbg3soxSCs9VNyh5VJd9.jpg",
    summary: "An artist and her subject develop an intimate bond on an isolated island.",
    collection: ["International Cinema", "Drama", "Award Winners", "Hidden Gems"]
  },
  {
    id: "past-lives",
    title: "Past Lives",
    year: 2023,
    director: "Celine Song",
    genres: ["Drama", "Romance"],
    rating: "7.8",
    runtime: "106 min",
    era: "Recent favorite",
    tone: "Quiet, graceful, aching",
    poster: "https://image.tmdb.org/t/p/w500/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg",
    summary: "Two childhood friends reconnect across decades and examine the lives they did not share.",
    collection: ["Drama", "Weekend Picks", "Award Winners"]
  },
  {
    id: "aftersun",
    title: "Aftersun",
    year: 2022,
    director: "Charlotte Wells",
    genres: ["Drama"],
    rating: "7.7",
    runtime: "102 min",
    era: "Recent favorite",
    tone: "Reflective, delicate, devastating",
    poster: "https://image.tmdb.org/t/p/w500/evKz85EKouVbIr51zy5fOtpNRPg.jpg",
    summary: "A woman reflects on a childhood holiday with her father and the memories that changed shape over time.",
    collection: ["Hidden Gems", "Drama", "Weekend Picks"]
  },
  {
    id: "the-social-network",
    title: "The Social Network",
    year: 2010,
    director: "David Fincher",
    genres: ["Drama", "Biography"],
    rating: "7.8",
    runtime: "120 min",
    era: "Modern classic",
    tone: "Sharp, chilly, propulsive",
    poster: "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    summary: "The rise of Facebook becomes a precise study of ambition, ownership, and isolation.",
    collection: ["Award Winners", "Drama", "Director Spotlight"]
  },
  {
    id: "there-will-be-blood",
    title: "There Will Be Blood",
    year: 2007,
    director: "Paul Thomas Anderson",
    genres: ["Drama"],
    rating: "8.2",
    runtime: "158 min",
    era: "Modern classic",
    tone: "Severe, volcanic, monumental",
    poster: "https://image.tmdb.org/t/p/w500/fa0RDkAlCec0STeMNAhPaF89q6U.jpg",
    summary: "An oilman's hunger for power turns ambition into spiritual corrosion.",
    collection: ["Drama", "Award Winners", "Classics"]
  },
  {
    id: "no-country-for-old-men",
    title: "No Country for Old Men",
    year: 2007,
    director: "Joel Coen, Ethan Coen",
    genres: ["Thriller", "Crime"],
    rating: "8.2",
    runtime: "122 min",
    era: "Modern classic",
    tone: "Bleak, exacting, suspenseful",
    poster: "https://image.tmdb.org/t/p/w500/bj1v6YKF8yHqA489VFfnQvOJpnc.jpg",
    summary: "A desert drug deal gone wrong draws three men into a brutal moral landscape.",
    collection: ["Award Winners", "Late Night Thrillers", "Thriller"]
  },
  {
    id: "zodiac",
    title: "Zodiac",
    year: 2007,
    director: "David Fincher",
    genres: ["Thriller", "Crime"],
    rating: "7.7",
    runtime: "157 min",
    era: "Modern classic",
    tone: "Obsessive, procedural, uneasy",
    poster: "https://image.tmdb.org/t/p/w500/6YmeO4pB7XTh8P8F960O1uA14JO.jpg",
    summary: "Reporters and investigators chase an elusive serial killer across years of uncertainty.",
    collection: ["Late Night Thrillers", "Director Spotlight", "Hidden Gems"]
  },
  {
    id: "prisoners",
    title: "Prisoners",
    year: 2013,
    director: "Denis Villeneuve",
    genres: ["Thriller", "Drama"],
    rating: "8.2",
    runtime: "153 min",
    era: "Modern favorite",
    tone: "Grim, tense, morally fraught",
    poster: "https://image.tmdb.org/t/p/w500/uhviyknTT5cEQXbn6vWIqfM4vGm.jpg",
    summary: "The disappearance of two girls pushes a father and detective toward desperate choices.",
    collection: ["Late Night Thrillers", "Director Spotlight", "Thriller"]
  },
  {
    id: "nightcrawler",
    title: "Nightcrawler",
    year: 2014,
    director: "Dan Gilroy",
    genres: ["Thriller", "Crime"],
    rating: "7.8",
    runtime: "118 min",
    era: "Modern favorite",
    tone: "Sleek, predatory, acidic",
    poster: "https://image.tmdb.org/t/p/w500/j9HrX8f7GbZQm1BrBiR40uFQZSb.jpg",
    summary: "An ambitious freelancer discovers that Los Angeles crime footage can become a business model.",
    collection: ["Late Night Thrillers", "Hidden Gems", "Thriller"]
  },
  {
    id: "se7en",
    title: "Se7en",
    year: 1995,
    director: "David Fincher",
    genres: ["Thriller", "Crime"],
    rating: "8.6",
    runtime: "127 min",
    era: "Modern classic",
    tone: "Bleak, meticulous, oppressive",
    poster: "https://image.tmdb.org/t/p/w500/69Sns8WoET6CfaYlIkHbla4l7nC.jpg",
    summary: "Two detectives pursue a killer staging murders around the seven deadly sins.",
    collection: ["Late Night Thrillers", "Director Spotlight", "Thriller"]
  },
  {
    id: "silence-of-the-lambs",
    title: "The Silence of the Lambs",
    year: 1991,
    director: "Jonathan Demme",
    genres: ["Thriller", "Horror"],
    rating: "8.6",
    runtime: "118 min",
    era: "Classic",
    tone: "Controlled, chilling, iconic",
    poster: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    summary: "An FBI trainee seeks insight from an imprisoned killer to catch another.",
    collection: ["Award Winners", "Late Night Thrillers", "Horror", "Classics"]
  },
  {
    id: "alien",
    title: "Alien",
    year: 1979,
    director: "Ridley Scott",
    genres: ["Horror", "Science Fiction"],
    rating: "8.5",
    runtime: "117 min",
    era: "Classic",
    tone: "Industrial, claustrophobic, terrifying",
    poster: "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
    summary: "A commercial spaceship crew is stalked by a hostile organism in deep space.",
    collection: ["Horror", "Science Fiction", "Late Night Thrillers", "Classics"]
  },
  {
    id: "the-shining",
    title: "The Shining",
    year: 1980,
    director: "Stanley Kubrick",
    genres: ["Horror", "Drama"],
    rating: "8.4",
    runtime: "146 min",
    era: "Classic",
    tone: "Icy, uncanny, iconic",
    poster: "https://image.tmdb.org/t/p/w500/xazWoLealQwEgqZ89MLZklLZD3k.jpg",
    summary: "A family becomes isolated in a haunted hotel as madness spreads through the corridors.",
    collection: ["Horror", "Late Night Thrillers", "Classics"]
  },
  {
    id: "hereditary",
    title: "Hereditary",
    year: 2018,
    director: "Ari Aster",
    genres: ["Horror", "Drama"],
    rating: "7.3",
    runtime: "127 min",
    era: "Recent favorite",
    tone: "Grief-stricken, occult, punishing",
    poster: "https://image.tmdb.org/t/p/w500/4GFPuL14eXi66V96xBWY73Y9PfR.jpg",
    summary: "A family tragedy reveals a terrifying inheritance hidden beneath grief.",
    collection: ["Horror", "Late Night Thrillers", "Modern Favorites"]
  },
  {
    id: "the-babadook",
    title: "The Babadook",
    year: 2014,
    director: "Jennifer Kent",
    genres: ["Horror", "Drama"],
    rating: "6.8",
    runtime: "94 min",
    era: "Modern favorite",
    tone: "Psychological, raw, intimate",
    poster: "https://image.tmdb.org/t/p/w500/qt3fqapeo94TfvMyld8P7gkpXLz.jpg",
    summary: "A mother and son are haunted by a sinister presence that may be grief itself.",
    collection: ["Horror", "Hidden Gems", "Late Night Thrillers"]
  },
  {
    id: "train-to-busan",
    title: "Train to Busan",
    year: 2016,
    director: "Yeon Sang-ho",
    genres: ["Horror", "Thriller"],
    rating: "7.6",
    runtime: "118 min",
    era: "Modern favorite",
    tone: "Fast, emotional, relentless",
    poster: "https://image.tmdb.org/t/p/w500/vNVFt6dtcqnI7hqa6LFBUibuFiw.jpg",
    summary: "Passengers fight to survive a zombie outbreak on a speeding train.",
    collection: ["International Cinema", "Horror", "Late Night Thrillers"]
  },
  {
    id: "pan-labyrinth",
    title: "Pan's Labyrinth",
    year: 2006,
    director: "Guillermo del Toro",
    genres: ["Fantasy", "Drama"],
    rating: "8.2",
    runtime: "118 min",
    era: "Modern classic",
    tone: "Dark, fairy-tale, mournful",
    poster: "https://image.tmdb.org/t/p/w500/2VVhikIxoztAXEDQZLOdtBsu6vf.jpg",
    summary: "A young girl escapes into a mythic underworld during postwar Spain.",
    collection: ["International Cinema", "Award Winners", "Hidden Gems"]
  },
  {
    id: "city-of-god",
    title: "City of God",
    year: 2002,
    director: "Fernando Meirelles, Katia Lund",
    genres: ["Crime", "Drama"],
    rating: "8.6",
    runtime: "130 min",
    era: "Modern classic",
    tone: "Kinetic, brutal, alive",
    poster: "https://image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg",
    summary: "A photographer grows up amid escalating violence in a Rio de Janeiro neighborhood.",
    collection: ["International Cinema", "Drama", "Editor's Picks"]
  },
  {
    id: "oldboy",
    title: "Oldboy",
    year: 2003,
    director: "Park Chan-wook",
    genres: ["Thriller", "Drama"],
    rating: "8.4",
    runtime: "120 min",
    era: "Modern classic",
    tone: "Operatic, brutal, twisted",
    poster: "https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg",
    summary: "A man imprisoned for years without explanation searches for the architect of his punishment.",
    collection: ["International Cinema", "Late Night Thrillers", "Mind-Bending Sci-Fi"]
  },
  {
    id: "rashomon",
    title: "Rashomon",
    year: 1950,
    director: "Akira Kurosawa",
    genres: ["Drama", "Classic"],
    rating: "8.2",
    runtime: "88 min",
    era: "Classic",
    tone: "Moral, spare, revolutionary",
    poster: "https://image.tmdb.org/t/p/w500/vL7Xw04nFMHwnvXRFCmYYAzMUvY.jpg",
    summary: "A crime is retold through competing testimonies that challenge truth itself.",
    collection: ["International Cinema", "Classics", "Award Winners"]
  },
  {
    id: "seven-samurai",
    title: "Seven Samurai",
    year: 1954,
    director: "Akira Kurosawa",
    genres: ["Action", "Drama"],
    rating: "8.6",
    runtime: "207 min",
    era: "Classic",
    tone: "Epic, humane, foundational",
    poster: "https://image.tmdb.org/t/p/w500/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
    summary: "Farmers hire masterless warriors to defend their village from bandits.",
    collection: ["International Cinema", "Classics", "Editor's Picks"]
  },
  {
    id: "bicycle-thieves",
    title: "Bicycle Thieves",
    year: 1948,
    director: "Vittorio De Sica",
    genres: ["Drama", "Classic"],
    rating: "8.3",
    runtime: "89 min",
    era: "Classic",
    tone: "Human, spare, devastating",
    poster: "https://image.tmdb.org/t/p/w500/7ZiSTZN5FWsphVmlwFVFfn5EOl.jpg",
    summary: "A father and son search Rome for the stolen bicycle needed for work.",
    collection: ["International Cinema", "Classics", "Hidden Gems"]
  },
  {
    id: "amelie",
    title: "Amelie",
    year: 2001,
    director: "Jean-Pierre Jeunet",
    genres: ["Romance", "Comedy"],
    rating: "8.3",
    runtime: "122 min",
    era: "Modern classic",
    tone: "Whimsical, precise, warm",
    poster: "https://image.tmdb.org/t/p/w500/oTKduWL2tpIKEmkAqF4mFEAWAsv.jpg",
    summary: "A shy Parisian waitress quietly changes the lives of people around her.",
    collection: ["International Cinema", "Weekend Picks", "Hidden Gems"]
  },
  {
    id: "your-name",
    title: "Your Name.",
    year: 2016,
    director: "Makoto Shinkai",
    genres: ["Animation", "Drama"],
    rating: "8.4",
    runtime: "106 min",
    era: "Modern favorite",
    tone: "Luminous, romantic, cosmic",
    poster: "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
    summary: "Two teenagers mysteriously swap bodies and search for each other across time and place.",
    collection: ["Animation", "International Cinema", "Weekend Picks"]
  },
  {
    id: "princess-mononoke",
    title: "Princess Mononoke",
    year: 1997,
    director: "Hayao Miyazaki",
    genres: ["Animation", "Fantasy"],
    rating: "8.4",
    runtime: "134 min",
    era: "Modern classic",
    tone: "Mythic, ecological, fierce",
    poster: "https://image.tmdb.org/t/p/w500/cMYCDADoLKLbB83g4WnJegaZimC.jpg",
    summary: "A prince becomes entangled in a conflict between forest spirits and human industry.",
    collection: ["Animation", "International Cinema", "Classics"]
  },
  {
    id: "wall-e",
    title: "WALL-E",
    year: 2008,
    director: "Andrew Stanton",
    genres: ["Animation", "Science Fiction"],
    rating: "8.4",
    runtime: "98 min",
    era: "Modern classic",
    tone: "Tender, visual, hopeful",
    poster: "https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
    summary: "A lonely trash-compacting robot discovers love and a reason for humanity to return home.",
    collection: ["Animation", "Science Fiction", "Award Winners", "Weekend Picks"]
  },
  {
    id: "coco",
    title: "Coco",
    year: 2017,
    director: "Lee Unkrich, Adrian Molina",
    genres: ["Animation", "Drama"],
    rating: "8.4",
    runtime: "105 min",
    era: "Modern favorite",
    tone: "Colorful, musical, heartfelt",
    poster: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
    summary: "A young musician enters the Land of the Dead and uncovers his family's history.",
    collection: ["Animation", "Award Winners", "Weekend Picks"]
  },
  {
    id: "how-to-train-your-dragon",
    title: "How to Train Your Dragon",
    year: 2010,
    director: "Dean DeBlois, Chris Sanders",
    genres: ["Animation", "Adventure"],
    rating: "8.1",
    runtime: "98 min",
    era: "Modern favorite",
    tone: "Warm, soaring, adventurous",
    poster: "https://image.tmdb.org/t/p/w500/ygGmAO60t8GyqUo9xYeYxSZAR3b.jpg",
    summary: "A young Viking forms an unlikely bond with a dragon and changes his village.",
    collection: ["Animation", "Weekend Picks"]
  },
  {
    id: "black-panther",
    title: "Black Panther",
    year: 2018,
    director: "Ryan Coogler",
    genres: ["Superhero", "Adventure"],
    rating: "7.3",
    runtime: "134 min",
    era: "Modern blockbuster",
    tone: "Regal, kinetic, cultural",
    poster: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    summary: "A newly crowned king faces a challenger with a radically different vision for Wakanda.",
    collection: ["Superhero", "Award Winners", "Modern Favorites"]
  },
  {
    id: "logan",
    title: "Logan",
    year: 2017,
    director: "James Mangold",
    genres: ["Superhero", "Drama"],
    rating: "8.1",
    runtime: "137 min",
    era: "Modern favorite",
    tone: "Rugged, mournful, intimate",
    poster: "https://image.tmdb.org/t/p/w500/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
    summary: "An aging mutant protects a young girl while confronting the end of his own legend.",
    collection: ["Superhero", "Drama", "Editor's Picks"]
  },
  {
    id: "guardians-of-the-galaxy",
    title: "Guardians of the Galaxy",
    year: 2014,
    director: "James Gunn",
    genres: ["Superhero", "Science Fiction"],
    rating: "8.0",
    runtime: "121 min",
    era: "Modern blockbuster",
    tone: "Loose, bright, irreverent",
    poster: "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
    summary: "A group of misfits becomes an unlikely team while chasing a powerful cosmic artifact.",
    collection: ["Superhero", "Science Fiction", "Weekend Picks"]
  },
  {
    id: "wonder-woman",
    title: "Wonder Woman",
    year: 2017,
    director: "Patty Jenkins",
    genres: ["Superhero", "Adventure"],
    rating: "7.3",
    runtime: "141 min",
    era: "Modern blockbuster",
    tone: "Earnest, mythic, bright",
    poster: "https://image.tmdb.org/t/p/w500/v4ncgZjG2Zu8ZW5al1vIZTsSjqX.jpg",
    summary: "An Amazon warrior leaves home to confront war and discover her own power.",
    collection: ["Superhero", "Modern Favorites"]
  },
  {
    id: "iron-man",
    title: "Iron Man",
    year: 2008,
    director: "Jon Favreau",
    genres: ["Superhero", "Action"],
    rating: "7.9",
    runtime: "126 min",
    era: "Modern blockbuster",
    tone: "Sleek, witty, foundational",
    poster: "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
    summary: "A weapons manufacturer builds a suit of armor and chooses a different future.",
    collection: ["Superhero", "Modern Favorites"]
  },
  {
    id: "the-wizard-of-oz",
    title: "The Wizard of Oz",
    year: 1939,
    director: "Victor Fleming",
    genres: ["Fantasy", "Classic"],
    rating: "8.1",
    runtime: "102 min",
    era: "Classic",
    tone: "Colorful, musical, timeless",
    poster: "https://image.tmdb.org/t/p/w500/bSA6DbAC5gdkaooU164lQUX6rVs.jpg",
    summary: "A Kansas girl journeys through Oz in search of home, courage, heart, and wisdom.",
    collection: ["Classics", "Weekend Picks"]
  },
  {
    id: "citizen-kane",
    title: "Citizen Kane",
    year: 1941,
    director: "Orson Welles",
    genres: ["Drama", "Classic"],
    rating: "8.3",
    runtime: "119 min",
    era: "Classic",
    tone: "Grand, investigative, influential",
    poster: "https://image.tmdb.org/t/p/w500/sav0jxhqiH0bPr2vZFU0Kjt2nZL.jpg",
    summary: "A reporter investigates the final word of a powerful media magnate.",
    collection: ["Classics", "Award Winners", "Drama"]
  },
  {
    id: "psycho",
    title: "Psycho",
    year: 1960,
    director: "Alfred Hitchcock",
    genres: ["Horror", "Thriller"],
    rating: "8.5",
    runtime: "109 min",
    era: "Classic",
    tone: "Sharp, shocking, controlled",
    poster: "https://image.tmdb.org/t/p/w500/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg",
    summary: "A secretary's disappearance leads to a remote motel and one of cinema's great shocks.",
    collection: ["Classics", "Horror", "Late Night Thrillers"]
  },
  {
    id: "rear-window",
    title: "Rear Window",
    year: 1954,
    director: "Alfred Hitchcock",
    genres: ["Thriller", "Classic"],
    rating: "8.5",
    runtime: "112 min",
    era: "Classic",
    tone: "Elegant, voyeuristic, suspenseful",
    poster: "https://image.tmdb.org/t/p/w500/ILVF0eJxHMddjxeQhswFtpMtqx.jpg",
    summary: "A housebound photographer suspects a neighbor of murder after watching from his window.",
    collection: ["Classics", "Late Night Thrillers"]
  },
  {
    id: "lawrence-of-arabia",
    title: "Lawrence of Arabia",
    year: 1962,
    director: "David Lean",
    genres: ["Adventure", "Drama"],
    rating: "8.3",
    runtime: "228 min",
    era: "Classic",
    tone: "Epic, vast, conflicted",
    poster: "https://image.tmdb.org/t/p/w500/AiAm0EtDvyGqNpVoieRw4u65vD1.jpg",
    summary: "A British officer becomes a legend and a contradiction during the Arab Revolt.",
    collection: ["Classics", "Award Winners", "Drama"]
  },
  {
    id: "goodfellas",
    title: "Goodfellas",
    year: 1990,
    director: "Martin Scorsese",
    genres: ["Crime", "Drama"],
    rating: "8.7",
    runtime: "145 min",
    era: "Modern classic",
    tone: "Fast, seductive, corrosive",
    poster: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    summary: "A mob associate rises through organized crime and watches the life collapse around him.",
    collection: ["Classics", "Drama", "Director Spotlight"]
  },
  {
    id: "heat",
    title: "Heat",
    year: 1995,
    director: "Michael Mann",
    genres: ["Crime", "Thriller"],
    rating: "8.3",
    runtime: "170 min",
    era: "Modern classic",
    tone: "Cool, procedural, expansive",
    poster: "https://image.tmdb.org/t/p/w500/umSVjVdbVwtx5ryCA2QXL44Durm.jpg",
    summary: "A master thief and relentless detective circle each other through Los Angeles.",
    collection: ["Late Night Thrillers", "Classics", "Hidden Gems"]
  },
  {
    id: "memento",
    title: "Memento",
    year: 2000,
    director: "Christopher Nolan",
    genres: ["Thriller", "Mystery"],
    rating: "8.4",
    runtime: "113 min",
    era: "Modern classic",
    tone: "Fragmented, tense, clever",
    poster: "https://image.tmdb.org/t/p/w500/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg",
    summary: "A man with short-term memory loss hunts for his wife's killer through notes and tattoos.",
    collection: ["Mind-Bending Sci-Fi", "Late Night Thrillers", "Director Spotlight"]
  },
  {
    id: "shutter-island",
    title: "Shutter Island",
    year: 2010,
    director: "Martin Scorsese",
    genres: ["Thriller", "Mystery"],
    rating: "8.2",
    runtime: "138 min",
    era: "Modern favorite",
    tone: "Gothic, paranoid, stormy",
    poster: "https://image.tmdb.org/t/p/w500/4GDy0PHYX3VRXUtwK5ysFbg3kEx.jpg",
    summary: "A marshal investigates a disappearance at an isolated psychiatric hospital.",
    collection: ["Late Night Thrillers", "Mind-Bending Sci-Fi", "Director Spotlight"]
  },
  {
    id: "gone-girl",
    title: "Gone Girl",
    year: 2014,
    director: "David Fincher",
    genres: ["Thriller", "Drama"],
    rating: "8.1",
    runtime: "149 min",
    era: "Modern favorite",
    tone: "Icy, media-savvy, vicious",
    poster: "https://image.tmdb.org/t/p/w500/qymaJhucquUwjpb8oiqynMeXnID.jpg",
    summary: "A woman's disappearance turns her husband into the center of a national spectacle.",
    collection: ["Late Night Thrillers", "Director Spotlight", "Modern Favorites"]
  },
  {
    id: "the-handmaiden",
    title: "The Handmaiden",
    year: 2016,
    director: "Park Chan-wook",
    genres: ["Thriller", "Drama"],
    rating: "8.1",
    runtime: "145 min",
    era: "Modern favorite",
    tone: "Luxurious, deceptive, sensual",
    poster: "https://image.tmdb.org/t/p/w500/dLlH4aNHdnmf62umnInL8xPlPzw.jpg",
    summary: "A con plot in colonial Korea becomes a layered game of desire and betrayal.",
    collection: ["International Cinema", "Late Night Thrillers", "Hidden Gems"]
  },
  {
    id: "burning",
    title: "Burning",
    year: 2018,
    director: "Lee Chang-dong",
    genres: ["Drama", "Mystery"],
    rating: "7.5",
    runtime: "148 min",
    era: "Recent favorite",
    tone: "Ambiguous, simmering, literary",
    poster: "https://image.tmdb.org/t/p/w500/kXiF80o74fE9gf3Utf9moAI7ar0.jpg",
    summary: "A young writer grows suspicious of a wealthy stranger after a woman disappears.",
    collection: ["International Cinema", "Hidden Gems", "Late Night Thrillers"]
  },
  {
    id: "roma",
    title: "Roma",
    year: 2018,
    director: "Alfonso Cuaron",
    genres: ["Drama", "International Cinema"],
    rating: "7.7",
    runtime: "135 min",
    era: "Recent favorite",
    tone: "Intimate, observational, luminous",
    poster: "https://image.tmdb.org/t/p/w500/dtIIyQyALk57ko5bjac7hi01YQ.jpg",
    summary: "A domestic worker's life unfolds against family change and political unrest in 1970s Mexico City.",
    collection: ["International Cinema", "Award Winners", "Drama"]
  },
  {
    id: "anatomy-of-a-fall",
    title: "Anatomy of a Fall",
    year: 2023,
    director: "Justine Triet",
    genres: ["Drama", "Thriller"],
    rating: "7.7",
    runtime: "152 min",
    era: "Recent favorite",
    tone: "Forensic, intimate, ambiguous",
    poster: "https://image.tmdb.org/t/p/w500/kQs6keheMwCxJxrzV83VUwFtHkB.jpg",
    summary: "A writer is put on trial after her husband's fatal fall exposes the fractures of their marriage.",
    collection: ["International Cinema", "Award Winners", "Late Night Thrillers"]
  },
  {
    id: "the-zone-of-interest",
    title: "The Zone of Interest",
    year: 2023,
    director: "Jonathan Glazer",
    genres: ["Drama", "Historical"],
    rating: "7.4",
    runtime: "105 min",
    era: "Recent favorite",
    tone: "Austere, chilling, formal",
    poster: "https://image.tmdb.org/t/p/w500/hUu9zyZmDd8VZegKi1iK1Vk0RYS.jpg",
    summary: "A commandant's family builds an ordinary life beside unimaginable horror.",
    collection: ["International Cinema", "Award Winners", "Drama"]
  },
  {
    id: "the-grand-budapest-hotel",
    title: "The Grand Budapest Hotel",
    year: 2014,
    director: "Wes Anderson",
    genres: ["Comedy", "Adventure"],
    rating: "8.1",
    runtime: "100 min",
    era: "Modern favorite",
    tone: "Precise, ornate, melancholy",
    poster: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    summary: "A concierge and lobby boy are swept into theft, war, and old-world elegance.",
    collection: ["Award Winners", "Weekend Picks", "Hidden Gems"]
  },
  {
    id: "knives-out",
    title: "Knives Out",
    year: 2019,
    director: "Rian Johnson",
    genres: ["Mystery", "Comedy"],
    rating: "7.9",
    runtime: "131 min",
    era: "Recent favorite",
    tone: "Witty, polished, playful",
    poster: "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
    summary: "A detective investigates a wealthy family's secrets after a mystery novelist dies.",
    collection: ["Weekend Picks", "Modern Favorites"]
  },
  {
    id: "the-nice-guys",
    title: "The Nice Guys",
    year: 2016,
    director: "Shane Black",
    genres: ["Comedy", "Crime"],
    rating: "7.4",
    runtime: "116 min",
    era: "Modern favorite",
    tone: "Loose, funny, stylish",
    poster: "https://image.tmdb.org/t/p/w500/clq4So9spa9cXk3MZy2iMdqkxP2.jpg",
    summary: "Two mismatched private eyes stumble into a conspiracy in 1970s Los Angeles.",
    collection: ["Hidden Gems", "Weekend Picks"]
  },
  {
    id: "edge-of-tomorrow",
    title: "Edge of Tomorrow",
    year: 2014,
    director: "Doug Liman",
    genres: ["Science Fiction", "Action"],
    rating: "7.9",
    runtime: "113 min",
    era: "Modern blockbuster",
    tone: "Clever, kinetic, repeatable",
    poster: "https://image.tmdb.org/t/p/w500/uUHvlkLavotfGsNtosDy8ShsIYF.jpg",
    summary: "A soldier trapped in a time loop learns to survive an alien invasion.",
    collection: ["Science Fiction", "Mind-Bending Sci-Fi", "Weekend Picks"]
  },
  {
    id: "minority-report",
    title: "Minority Report",
    year: 2002,
    director: "Steven Spielberg",
    genres: ["Science Fiction", "Thriller"],
    rating: "7.6",
    runtime: "145 min",
    era: "Modern classic",
    tone: "Sleek, paranoid, propulsive",
    poster: "https://image.tmdb.org/t/p/w500/ccqpHq5tk5W4ymbSbuoy4uYOxFI.jpg",
    summary: "A future police officer is accused of a murder he has not yet committed.",
    collection: ["Science Fiction", "Late Night Thrillers", "Mind-Bending Sci-Fi"]
  },
  {
    id: "under-the-skin",
    title: "Under the Skin",
    year: 2013,
    director: "Jonathan Glazer",
    genres: ["Science Fiction", "Horror"],
    rating: "6.3",
    runtime: "108 min",
    era: "Modern favorite",
    tone: "Alien, abstract, unsettling",
    poster: "https://image.tmdb.org/t/p/w500/55wmcXJIDYITr7JDijJTdvwSaAv.jpg",
    summary: "A mysterious woman drives through Scotland, observing and consuming human vulnerability.",
    collection: ["Hidden Gems", "Mind-Bending Sci-Fi", "Horror"]
  },
  {
    id: "the-fall-guy",
    title: "The Fall Guy",
    year: 2024,
    director: "David Leitch",
    genres: ["Action", "Comedy"],
    rating: "6.9",
    runtime: "126 min",
    era: "Recent favorite",
    tone: "Breezy, stunt-driven, charming",
    poster: "https://image.tmdb.org/t/p/w500/aBkqu7EddWK7qmY4grL4I6edx2h.jpg",
    summary: "A stuntman searches for a missing star while trying to repair an old romance.",
    collection: ["Weekend Picks", "Modern Favorites"]
  },
  {
    id: "top-gun-maverick",
    title: "Top Gun: Maverick",
    year: 2022,
    director: "Joseph Kosinski",
    genres: ["Action", "Drama"],
    rating: "8.2",
    runtime: "131 min",
    era: "Recent favorite",
    tone: "Clean, thrilling, emotional",
    poster: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    summary: "A veteran pilot trains elite graduates for a dangerous mission and faces his own past.",
    collection: ["Modern Favorites", "Weekend Picks", "Trending"]
  },
  {
    id: "barbie",
    title: "Barbie",
    year: 2023,
    director: "Greta Gerwig",
    genres: ["Comedy", "Fantasy"],
    rating: "6.8",
    runtime: "114 min",
    era: "Recent favorite",
    tone: "Bright, self-aware, playful",
    poster: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    summary: "A doll leaves a perfect world to confront identity, expectations, and reality.",
    collection: ["Modern Favorites", "Weekend Picks"]
  },
  {
    id: "oppenheimer-companion",
    title: "Dunkirk",
    year: 2017,
    director: "Christopher Nolan",
    genres: ["Drama", "War"],
    rating: "7.8",
    runtime: "107 min",
    era: "Modern blockbuster",
    tone: "Tense, spatial, relentless",
    poster: "https://image.tmdb.org/t/p/w500/b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg",
    summary: "Allied soldiers fight time, distance, and fear during the evacuation of Dunkirk.",
    collection: ["Director Spotlight", "Award Winners", "Drama"]
  }
);

const CINEVERSE_COLLECTIONS = [
  {
    id: "hidden-gems",
    title: "Hidden Gems",
    eyebrow: "Under the radar",
    description: "Sharp discoveries that reward a little curiosity.",
    collection: "Hidden Gems",
    featuredIds: ["aftersun", "the-nice-guys", "burning", "under-the-skin"]
  },
  {
    id: "award-winners",
    title: "Award Winners",
    eyebrow: "Acclaimed cinema",
    description: "Prestige films with craft, reputation, and staying power.",
    collection: "Award Winners",
    featuredIds: ["moonlight", "parasite", "roma", "anatomy-of-a-fall"]
  },
  {
    id: "director-spotlight",
    title: "Director Spotlight",
    eyebrow: "Signature voices",
    description: "Distinct filmmakers whose style shapes the experience.",
    collection: "Director Spotlight",
    featuredIds: ["blade-runner-2049", "zodiac", "goodfellas", "oppenheimer-companion"]
  },
  {
    id: "mind-bending-sci-fi",
    title: "Mind-Bending Sci-Fi",
    eyebrow: "Big ideas",
    description: "Puzzle boxes, futures, and realities that keep shifting.",
    collection: "Mind-Bending Sci-Fi",
    featuredIds: ["inception", "memento", "ex-machina", "edge-of-tomorrow"]
  },
  {
    id: "late-night-thrillers",
    title: "Late Night Thrillers",
    eyebrow: "After dark",
    description: "Tense, polished picks built for one more scene.",
    collection: "Late Night Thrillers",
    featuredIds: ["prisoners", "se7en", "the-handmaiden", "nightcrawler"]
  },
  {
    id: "weekend-picks",
    title: "Weekend Picks",
    eyebrow: "Easy to recommend",
    description: "Elegant, generous films for a relaxed discovery session.",
    collection: "Weekend Picks",
    featuredIds: ["knives-out", "your-name", "wall-e", "top-gun-maverick"]
  }
];
